id: brimstone-97f44
game: diablo-4
type: Mount
catalog: game
tags:
  - diablo-4
  - normal
  - mount
rarity: Normal
itemTypeName: Mount
classes: null
slots: null
value: 57
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
