id: reins-of-the-bloody-liquid-steed-10bf0
game: diablo-4
type: Mount
tags:
  - diablo-4
  - normal
  - mount
rarity: Normal
itemTypeName: Mount
classes: null
slots: null
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
