id: cruor-s-embrace-2137c
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes:
  - Necromancer
slots:
  - Hands
value: 93
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
