id: barb-and-bite-a64b9
game: diablo-4
type: Quarterstaff
catalog: game
tags:
  - diablo-4
  - special
  - quarterstaff
rarity: Special
itemTypeName: Quarterstaff
classes:
  - Spiritborn
slots:
  - Main Hand
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
