id: tun-e9603
game: diablo-4
type: Rune of Invocation
catalog: game
tags:
  - diablo-4
  - common
  - rune of invocation
rarity: Common
itemTypeName: Rune of Invocation
classes: null
slots: null
value: 27
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
