id: totem-51568
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - totem
rarity: Special
itemTypeName: Totem
classes:
  - Druid
slots:
  - Off-Hand
value: 31
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
