id: lightweight-stock-1cd77
game: arc-raiders
type: Modification
tags:
  - epic
  - modification
rarity: Epic
subtype: null
value: 5000
stat_block:
  weight: 0.25
  reducedEquipTime: 30
  compatibleWeapons: Rattler, Kettle, Ferro, Renegade, Hullcracker
  increasedADSSpeed: 200
  reducedUnequipTime: 30
  increasedVerticalRecoil: 50
  increasedRecoilRecoveryTime: 50
loadout_slots:
  - backpack
  - safePocket
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
