id: skyhunter-53975
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - bow
rarity: Legendary
itemTypeName: Bow
classes:
  - Rogue
slots:
  - Main Hand
value: 44
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
