id: loyalty-s-mantle-02a75
game: diablo-4
type: Boots
catalog: game
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Spiritborn
slots:
  - Feet
value: 23
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
