id: ph-fear-jewel-aa7c9
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - horadric jewel
rarity: Unique
itemTypeName: Horadric Jewel
classes: null
slots: null
value: 18
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
