id: ancient-fort-security-code-32ac4
game: arc-raiders
type: item
tags:
  - common
  - key
rarity: Common
subtype: null
value: 0
stat_block:
  weight: 0.25
loadout_slots: []
workbench: null
flavor_text: Can only be used during Locked Gate
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
