id: paladin-guard-7d4f1
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - temper manual
rarity: Unique
itemTypeName: Temper Manual
classes:
  - Paladin
slots: null
value: 26
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
