id: bow-6d1bf
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - bow
rarity: Special
itemTypeName: Bow
classes:
  - Rogue
slots:
  - Main Hand
value: 50
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
