id: tribute-of-ascendance-resolute-30c57
game: diablo-4
type: Nightmare Sigil
catalog: game
tags:
  - diablo-4
  - legendary
  - nightmare sigil
rarity: Legendary
itemTypeName: Nightmare Sigil
classes: null
slots: null
value: 99
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
