id: advanced-electrical-components-b8e11
game: arc-raiders
type: item
tags:
  - rare
  - refined material
rarity: Rare
subtype: null
value: 1750
stat_block:
  weight: 1
  stackSize: 5
loadout_slots:
  - backpack
  - safePocket
workbench: Refiner
flavor_text: "Used to craft: Tactical Mk. 3 (Defensive), Combat Mk. 3
  (Flanking), Combat Mk. 3 (Aggressive), Looting Mk. 3 (Cautious), Tactical Mk.
  3 (Healing)"
ammo_type: null
shield_type: null
loot_area: Electrical
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
