id: grand-sword-d5a03
game: diablo-4
type: Two-Handed Sword
catalog: game
tags:
  - diablo-4
  - rare
  - two-handed sword
rarity: Rare
itemTypeName: Two-Handed Sword
classes:
  - Barbarian
  - Necromancer
  - Paladin
slots:
  - Main Hand
value: 14
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
