id: jade-glaive-79fb2
game: diablo-4
type: Glaive
tags:
  - diablo-4
  - unique
  - glaive
rarity: Unique
itemTypeName: Glaive
classes:
  - Spiritborn
slots:
  - Main Hand
value: 25
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
