id: dread-poleaxe
game: diablo-4
type: Polearm
catalog: game
tags:
  - diablo-4
  - unique
  - polearm
rarity: Unique
itemTypeName: Polearm
classes:
  - Barbarian
  - Druid
  - Spiritborn
slots:
  - Main Hand
value: 33
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
