id: torrente-iii-c80e5
game: arc-raiders
type: item
tags:
  - rare
  - weapon
rarity: Rare
subtype: null
value: 13000
stat_block:
  range: 49.9
  damage: 8
  weight: 12
  agility: 37.7
  stealth: 1
  fireRate: 58.3
  stability: 74.2
  magazineSize: 80
  reducedReloadTime: 30
  reducedDurabilityBurnRate: 46
loadout_slots: []
workbench: Weapon Bench I
flavor_text: Somewhat effective against ARC armor plating
ammo_type: Medium
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
