id: sunbird-s-gorget-11dc8
game: diablo-4
type: Amulet
catalog: game
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes:
  - Spiritborn
slots:
  - Neck
value: 47
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
