id: rattler-i-efcf7
game: arc-raiders
type: Weapon
catalog: game
tags:
  - common
  - weapon
rarity: Common
subtype: Assault Rifle
value: 1750
stat_block:
  ammo: medium
  range: 56.2
  damage: 9
  weight: 6
  agility: 54.8
  stealth: 14
  fireRate: 33.3
  stability: 72.2
  firingMode: Auto
  magazineSize: 10
loadout_slots:
  - weapon
workbench: Weapon Bench
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
