id: electrical-components
game: arc-raiders
type: Refined Material
catalog: game
tags:
  - uncommon
  - refined material
rarity: Uncommon
subtype: null
value: 640
stat_block:
  weight: 0.5
  stackSize: 10
loadout_slots:
  - backpack
  - safePocket
workbench: Refiner
flavor_text: "Used to craft: Tactical Mk.2, Combat Mk.2, Looting Mk.2, Advanced
  Electrical Components, Surge Shield Recharger"
ammo_type: null
shield_type: null
loot_area: Electrical
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
