id: nagu-c5d1e
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - rune of ritual
rarity: Unique
itemTypeName: Rune of Ritual
classes: null
slots: null
value: 260
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
