id: stygian-stone-8266d
game: diablo-4
type: Lair Boss Key
catalog: game
tags:
  - diablo-4
  - common
  - lair boss key
rarity: Common
itemTypeName: Lair Boss Key
classes: null
slots: null
value: 50
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
