id: guthr-s-shadow-52bd5
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - two-handed axe
rarity: Special
itemTypeName: Two-Handed Axe
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
slots:
  - Main Hand
value: 21
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
