id: azmodan-s-spoils-1f5d5
game: diablo-4
type: Grand Cache
catalog: game
tags:
  - diablo-4
  - unique
  - grand cache
rarity: Unique
itemTypeName: Grand Cache
classes: null
slots: null
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
