id: solemn-reflection-c6f44
game: diablo-4
type: Experience Tome
catalog: game
tags:
  - diablo-4
  - rare
  - experience tome
rarity: Rare
itemTypeName: Experience Tome
classes: null
slots: null
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
