id: two-handed-axe-2b4e0
game: diablo-4
type: Two-Handed Axe
catalog: game
tags:
  - diablo-4
  - special
  - two-handed axe
rarity: Special
itemTypeName: Two-Handed Axe
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
slots:
  - Main Hand
value: 27
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
