id: windforce-419e6
game: diablo-4
type: Bow
catalog: game
tags:
  - diablo-4
  - legendary
  - bow
rarity: Legendary
itemTypeName: Bow
classes:
  - Rogue
slots:
  - Main Hand
value: 65
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
