id: leaden-mace
game: diablo-4
type: Mace
catalog: game
tags:
  - diablo-4
  - rare
  - mace
rarity: Rare
itemTypeName: Mace
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
  - Sorcerer
  - Warlock
slots:
  - Main Hand
  - Off-Hand
value: 9
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
