id: broken-handheld-radio-dec97
game: arc-raiders
type: item
tags:
  - rare
  - recyclable
rarity: Rare
subtype: null
value: 2000
stat_block:
  weight: 3
  stackSize: 3
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: Security
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
