id: infernal-hordes-compass-5ef29
game: diablo-4
type: Nightmare Sigil
catalog: game
tags:
  - diablo-4
  - common
  - nightmare sigil
rarity: Common
itemTypeName: Nightmare Sigil
classes: null
slots: null
value: 34
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
