id: glyph-charged-79be2
game: diablo-4
type: Paragon Glyph
catalog: game
tags:
  - diablo-4
  - rare
  - paragon glyph
rarity: Rare
itemTypeName: Paragon Glyph
classes:
  - Sorcerer
slots: null
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images: []
