id: dream-catcher-0d6c1
game: diablo-4
type: Focus
tags:
  - diablo-4
  - unique
  - focus
rarity: Unique
itemTypeName: Focus
classes:
  - Necromancer
  - Sorcerer
slots:
  - Off-Hand
value: 15
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
