id: sunbringer-sabatons
game: diablo-4
type: Boots
catalog: game
tags:
  - diablo-4
  - special
  - boots
rarity: Special
itemTypeName: Boots
classes:
  - Paladin
slots:
  - Feet
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
