id: uncertain-governing-stone-cache
game: diablo-4
type: Crafted Cache
catalog: game
tags:
  - diablo-4
  - normal
  - crafted cache
rarity: Normal
itemTypeName: Crafted Cache
classes: null
slots: null
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
