id: arreat-s-bearing-3a28b
game: diablo-4
type: Pants
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes:
  - Barbarian
slots:
  - Legs
value: 113
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
