id: magnetic-accelerator-9c6fa
game: arc-raiders
type: item
tags:
  - epic
  - refined material
rarity: Epic
subtype: null
value: 5500
stat_block:
  weight: 1
  stackSize: 3
loadout_slots: []
workbench: Refiner
flavor_text: null
ammo_type: null
shield_type: null
loot_area: Exodus
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
