id: dam-staff-room-key-20a4c
game: arc-raiders
type: Key
catalog: game
tags:
  - uncommon
  - key
rarity: Uncommon
subtype: null
value: 100
stat_block:
  weight: 0.25
  stackSize: 1
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations:
  - id: 5ff5069c-aae7-6b4b-18d0-c6973283c2ea
    map: dam
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
