id: bobcat-iv-0dc19
game: arc-raiders
type: Weapon
tags:
  - epic
  - weapon
rarity: Epic
subtype: SMG
value: 27000
stat_block:
  range: 44
  damage: 6
  weight: 7
  agility: 73.1
  stealth: 21
  fireRate: 66.7
  stability: 45.9
  magazineSize: 20
  reducedReloadTime: 40
  reducedMaxShotDispersion: 45
loadout_slots: []
workbench: null
flavor_text: Weak against ARC armor plating
ammo_type: light
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
