id: zir-s-bloody-skull-0f949
game: diablo-4
type: item
tags:
  - diablo-4
  - normal
  - trophy
rarity: Normal
itemTypeName: Trophy
classes: null
slots:
  - Trophy
value: 25
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
