name: Arc Raiders
logo: /statics/games/arc-raiders/logo.svg
developer: Embark Studios
publisher: Embark Studios
release: 2025-10-30
platforms:
  - PC
  - PlayStation
  - Xbox
genres:
  - extraction
  - shooter
modes:
  - pvpve