id: kilt-of-blackwing-5d53c
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Druid
slots:
  - Feet
value: 22
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
