id: greater-collection-of-gold-adf69
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - grand cache
rarity: Unique
itemTypeName: Grand Cache
classes: null
slots: null
value: 25
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
