id: doombringer-crucible-76538
game: diablo-4
type: Sword
catalog: game
tags:
  - diablo-4
  - mythic
  - sword
rarity: Mythic
itemTypeName: Sword
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
  - Rogue
  - Sorcerer
slots:
  - Main Hand
  - Off-Hand
value: 45
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
