id: heir-of-perdition-c9c68
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - mythic
  - helm
rarity: Mythic
itemTypeName: Helm
classes: null
slots:
  - Head
value: 952
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
