id: angled-grip-ii
game: arc-raiders
type: Modification
catalog: game
tags:
  - uncommon
  - modification
rarity: Uncommon
subtype: null
value: 2000
stat_block:
  value: 2000
  weight: 0.5
  stackSize: 1
loadout_slots:
  - backpack
  - safePocket
workbench: null
flavor_text: 30% Reduced Horizontal Recoil
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
