id: path-of-trag-oul-c816c
game: diablo-4
type: Boots
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Necromancer
slots:
  - Feet
value: 41
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
