id: heart-of-anima
game: diablo-4
type: Occult Gem
catalog: game
tags:
  - diablo-4
  - common
  - occult gem
rarity: Common
itemTypeName: Occult Gem
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
