id: rogue-persistence-legacy-b2204
game: diablo-4
type: Temper Manual
catalog: game
tags:
  - diablo-4
  - rare
  - temper manual
rarity: Rare
itemTypeName: Temper Manual
classes: null
slots: null
value: 20
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
