id: awoken-demigod-helm-7d00b
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - special
  - helm
rarity: Special
itemTypeName: Helm
classes:
  - Barbarian
slots:
  - Head
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
