id: plastic-parts
game: arc-raiders
type: Basic Material
catalog: game
tags:
  - common
  - basic material
rarity: Common
subtype: null
value: 60
stat_block:
  weight: 0.1
  stackSize: 50
loadout_slots:
  - backpack
  - safePocket
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: Technological, Commercial, Residential
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
