id: resplendent-spark-8f3dd
game: diablo-4
type: Crafting Material
catalog: game
tags:
  - diablo-4
  - mythic
  - crafting material
rarity: Mythic
itemTypeName: Crafting Material
classes: null
slots: null
value: 147
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
