id: disciple-innovation-88925
game: diablo-4
type: item
tags:
  - diablo-4
  - rare
  - temper manual
rarity: Rare
itemTypeName: Temper Manual
classes:
  - Paladin
slots: null
value: 51
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
