id: torrente-ii
game: arc-raiders
type: Weapon
catalog: game
tags:
  - rare
  - weapon
rarity: Rare
subtype: null
value: 10000
stat_block:
  range: 49.9
  damage: 8
  weight: 12
  agility: 37.7
  stealth: 1
  fireRate: 58.3
  stability: 74.2
  magazineSize: 70
  reducedReloadTime: 15
  reducedDurabilityBurnRate: 23
loadout_slots: []
workbench: Weapon Bench I
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
