id: judgment-of-auriel-23c27
game: diablo-4
type: Amulet
catalog: game
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes:
  - Paladin
slots:
  - Neck
value: 43
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
