id: exceptional-helm
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - unique
  - helm
rarity: Unique
itemTypeName: Helm
classes: null
slots:
  - Head
value: 10
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
