id: disciple-innovation-21289
game: diablo-4
type: Temper Manual
catalog: game
tags:
  - diablo-4
  - unique
  - temper manual
rarity: Unique
itemTypeName: Temper Manual
classes:
  - Paladin
slots: null
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
