id: scroll-of-butchery-742ea
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - scroll
rarity: Unique
itemTypeName: Scroll
classes: null
slots: null
value: 36
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
