id: equalizer-e45c4
game: arc-raiders
type: Weapon
catalog: game
tags:
  - legendary
  - weapon
rarity: Legendary
subtype: Special
value: 27500
stat_block:
  ammo: energy
  damage: 8
  weight: 14
  agility: 44.6
  fireRate: 33.33
  stability: 84.6
  firingMode: Auto
  magazineSize: 50
loadout_slots:
  - weapon
workbench: Weapon Bench 3
flavor_text: Extremely effective against ARC armor plating and limbs
ammo_type: Energy
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
