# Akao Rules Configuration
# This file controls the behavior of the .akao/rules system

# Global rule settings
global:
  default_enabled: true
  parallel_execution: false
  auto_fix: false
  advanced_math: true
  lazy_loading: true
  
# Logging configuration
logging:
  level: info
  format: structured
  output: console
  audit_log: .akao/logs/audit.log
  
# Category settings
categories:
  structure:
    enabled: true
    severity: error
    description: "Code structure and organization rules"
    
  interface:
    enabled: true
    severity: warning
    description: "Interface design and compliance rules"
    
  language:
    enabled: true
    severity: error
    description: "Language-specific validation rules"
    
  build:
    enabled: false
    severity: info
    description: "Build system and configuration rules"
    
  custom:
    enabled: true
    severity: error
    description: "Project-specific custom rules"
    
  philosophy:
    enabled: true
    severity: error
    description: "Philosophy compliance and formal proof rules"

# File type mappings
file_types:
  cpp:
    extensions: ["*.cpp", "*.hpp", "*.cc", "*.hh", "*.cxx", "*.hxx"]
    language: "cpp"
    
  yaml:
    extensions: ["*.yaml", "*.yml"]
    language: "yaml"
    
  akao:
    extensions: ["*.a"]
    language: "akao"
    
  markdown:
    extensions: ["*.md", "*.markdown"]
    language: "markdown"
    
  cmake:
    extensions: ["CMakeLists.txt", "*.cmake"]
    language: "cmake"

# Path exclusions
exclude_paths:
  - "build/"
  - "node_modules/"
  - ".git/"
  - ".vscode/"
  - "*.tmp"
  - "*.bak"
  - "*.swp"
  - "artifacts/"
  - "sandbox/"

# Include patterns (if specified, only these paths are validated)
include_paths: []

# Performance settings
performance:
  max_threads: 0  # 0 = auto-detect
  cache_enabled: true
  cache_ttl_seconds: 300
  max_file_size_mb: 10
  
# Validation modes
validation_modes:
  strict:
    all_rules_enabled: true
    fail_on_warning: true
    require_philosophy_compliance: true
    
  development:
    skip_heavy_rules: true
    enable_auto_fix: true
    parallel_execution: true
    
  ci:
    parallel_execution: true
    structured_output: true
    fail_fast: false
    
  production:
    all_rules_enabled: true
    audit_logging: true
    formal_proofs: true

# Rule dependencies
dependencies:
  - rule_id: "structure:one_class_per_file"
    depends_on: ["structure:file_organization"]
    
  - rule_id: "interface:command_parity"
    depends_on: ["structure:one_class_per_file", "language:cpp_standards"]

# Auto-fix settings
auto_fix:
  enabled: false
  backup_original: true
  backup_directory: .akao/backups
  max_fixes_per_file: 10
  
# Notification settings
notifications:
  enabled: false
  webhook_url: ""
  slack_channel: ""
  email_recipients: []

# Plugin settings
plugins:
  enabled: []
  disabled: []
  search_paths: [".akao/plugins"]

# Rule overrides (per-file or per-directory)
overrides:
  - path: "tests/"
    rules:
      - rule_id: "structure:one_class_per_file"
        enabled: false
        reason: "Test files may contain multiple test classes"
        
  - path: "examples/"
    categories:
      - category: "structure"
        severity: "warning"
        reason: "Examples are for demonstration purposes"