id: purified-eye-of-belial-a62af
game: diablo-4
type: Purified Essence
tags:
  - diablo-4
  - legendary
  - purified essence
rarity: Legendary
itemTypeName: Purified Essence
classes: null
slots: null
value: 26
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
