id: exodus-modules-94ed8
game: arc-raiders
type: item
tags:
  - epic
  - topside material
rarity: Epic
subtype: null
value: 2750
stat_block:
  weight: 1
  stackSize: 3
loadout_slots: []
workbench: null
flavor_text: "Used to craft: Tempest, Vulcano, Hullcracker, Bobcat, Snap Hook"
ammo_type: null
shield_type: null
loot_area: Exodus
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
