id: resource-aspect-dd31f
game: diablo-4
type: Aspect
catalog: game
tags:
  - diablo-4
  - special
  - aspect
rarity: Special
itemTypeName: Aspect
classes: null
slots: null
value: 10
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
