id: skartaran-basilisk-6938a
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - mount
rarity: Special
itemTypeName: Mount
classes: null
slots: null
value: 17
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
