id: meaty-offering
game: diablo-4
type: Butcher Token
catalog: game
tags:
  - diablo-4
  - epic
  - butcher token
rarity: Epic
itemTypeName: Butcher Token
classes: null
slots: null
value: 57
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
