id: tactical-mk-3-revival-e0a48
game: arc-raiders
type: Augment
catalog: game
tags:
  - epic
  - augment
rarity: Epic
subtype: null
value: 5000
stat_block:
  weight: 3
  backpackSlots: 16
  quickUseSlots: 5
  weightLimitKg: 65
  safePocketSlots: 2
  shieldCompatibility: Light
loadout_slots: []
workbench: null
flavor_text: Restores 1 health every 5 seconds. When damage is taken, the effect
  is paused for 30 seconds.
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
