id: goblin-s-rare-kurast-undercity-tributes
game: diablo-4
type: Goblin Cache
catalog: game
tags:
  - diablo-4
  - rare
  - goblin cache
rarity: Rare
itemTypeName: Goblin Cache
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
