id: boots-442c2
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - boots
rarity: Special
itemTypeName: Boots
classes: null
slots:
  - Feet
value: 366
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
