id: guise-of-war-be33b
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes:
  - Barbarian
slots:
  - Head
value: 13
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
