id: xan-8460b
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - rune of invocation
rarity: Unique
itemTypeName: Rune of Invocation
classes: null
slots: null
value: 273
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
