id: ingolith-5aff9
game: diablo-4
type: Crafting Material
tags:
  - diablo-4
  - normal
  - crafting material
rarity: Normal
itemTypeName: Crafting Material
classes: null
slots: null
value: 21
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
