id: glyph-outmatch-16a5d
game: diablo-4
type: Paragon Glyph
catalog: game
tags:
  - diablo-4
  - rare
  - paragon glyph
rarity: Rare
itemTypeName: Paragon Glyph
classes:
  - Druid
slots: null
value: 13
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images: []
