id: asheara-s-khanjar-crucible-5014e
game: diablo-4
type: Dagger
catalog: game
tags:
  - diablo-4
  - legendary
  - dagger
rarity: Legendary
itemTypeName: Dagger
classes:
  - Rogue
slots:
  - Main Hand
  - Off-Hand
value: 32
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
