id: extended-shotgun-mag-ii-blueprint
game: arc-raiders
type: Blueprint
catalog: game
tags:
  - legendary
  - blueprint
rarity: Legendary
subtype: null
value: 5000
stat_block: null
loadout_slots: []
workbench: Weapon Bench
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
