id: paingorger-s-gauntlets-8a4e0
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes: null
slots:
  - Hands
value: 387
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
