id: tempest-roar-0070e
game: diablo-4
type: Boots
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Druid
slots:
  - Feet
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
