id: rank-vi-capstone-cache-fb0b6
game: diablo-4
type: Season Ranking Cache
catalog: game
tags:
  - diablo-4
  - legendary
  - season ranking cache
rarity: Legendary
itemTypeName: Season Ranking Cache
classes: null
slots: null
value: 20
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
