id: demonblade-crucible-e6345
game: diablo-4
type: Two-Handed Sword
tags:
  - diablo-4
  - unique
  - two-handed sword
rarity: Unique
itemTypeName: Two-Handed Sword
classes:
  - Barbarian
  - Necromancer
  - Paladin
slots:
  - Main Hand
value: 35
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
