id: death-s-reach-67592
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - two-handed scythe
rarity: Unique
itemTypeName: Two-Handed Scythe
classes:
  - Necromancer
slots:
  - Main Hand
value: 22
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
