id: curse-of-viz-jun-present-2d723
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - horse armor
rarity: Special
itemTypeName: Horse Armor
classes: null
slots:
  - Mount Armor
value: 18
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
