id: oblivion-skull
game: diablo-4
type: Focus
catalog: game
tags:
  - diablo-4
  - special
  - focus
rarity: Special
itemTypeName: Focus
classes:
  - Necromancer
  - Sorcerer
  - Warlock
slots:
  - Off-Hand
value: 24
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
