id: lamentation-choker-6fc5b
game: diablo-4
type: Amulet
tags:
  - diablo-4
  - unique
  - amulet
rarity: Unique
itemTypeName: Amulet
classes: null
slots:
  - Neck
value: 16
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
