id: x-fal-s-corroded-signet-d6917
game: diablo-4
type: Pants
catalog: game
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes: null
slots:
  - Legs
value: 25
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
