id: renegade-ii-f8c43
game: arc-raiders
type: Weapon
tags:
  - rare
  - weapon
rarity: Rare
subtype: null
value: 10000
stat_block:
  range: 68.8
  damage: 35
  weight: 10
  agility: 55.8
  stealth: 16
  fireRate: 21
  stability: 85.7
  magazineSize: 8
  increasedFireRate: 25
  reducedDurabilityBurnRate: 23
  reducedDispersionRecoveryTime: 16.6
loadout_slots: []
workbench: Weapon Bench I
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
