id: elements-of-hatred-20575
game: diablo-4
type: Reputation Cache
catalog: game
tags:
  - diablo-4
  - epic
  - reputation cache
rarity: Epic
itemTypeName: Reputation Cache
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
