id: slaughterhouse-2c55a
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - nightmare sigil
rarity: Special
itemTypeName: Nightmare Sigil
classes: null
slots: null
value: 46
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
