id: dolmen-stone-c8d10
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes:
  - Druid
slots:
  - Neck
value: 60
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
