name: Diablo IV
developer: Blizzard Entertainment
publisher: Blizzard Entertainment
release: 2023-06-01
platforms:
  - PC
  - PlayStation
  - Xbox
genres:
  - action
  - rpg
  - dungeon
modes:
  - pve
  - pvp