id: nightslayer-s-widebrim-8cdc9
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - special
  - helm
rarity: Special
itemTypeName: Helm
classes:
  - Druid
slots:
  - Head
value: 13
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
