id: governing-stone-autodefense-77890
game: diablo-4
type: Senechal Power Module
catalog: game
tags:
  - diablo-4
  - unique
  - senechal power module
rarity: Unique
itemTypeName: Senechal Power Module
classes: null
slots: null
value: 16
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
