id: angled-grip-i-a9d3e
game: arc-raiders
type: Modification
tags:
  - common
  - modification
rarity: Common
subtype: null
value: 640
stat_block:
  weight: 0.25
  stackSize: 1
  compatibleWeapons: Ferro, Kettle, Rattler, Stitcher, Arpeggio, II toro, Venator,
    Bobcat, Tempest, Vulcano
loadout_slots:
  - backpack
  - safePocket
workbench: Weapon Bench
flavor_text: 20% Reduced Horizontal Recoil
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
