Le_Domain='akao.io'
Le_Alt='no'
Le_Webroot='/home/x/akao'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/3283425605/505206195075'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/3283425605/505206195075'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/06b6744cf6a83f85fa2081a56af76499ba23'
Le_CertCreateTime='1777379044'
Le_CertCreateTimeStr='2026-04-28T12:24:04Z'
Le_NextRenewTimeStr='2026-05-27T12:24:04Z'
Le_NextRenewTime='1779884644'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/home/x/akao/.certs/prod-key.pem'
Le_ReloadCmd='__ACME_BASE64__START_c3VkbyBzeXN0ZW1jdGwgcmVzdGFydCBha2Fv__ACME_BASE64__END_'
Le_RealFullChainPath='/home/x/akao/.certs/prod-cert.pem'
