id: horadric-secrets-c96df
game: diablo-4
type: Lorebook
catalog: game
tags:
  - diablo-4
  - common
  - lorebook
rarity: Common
itemTypeName: Lorebook
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Rogue
  - Sorcerer
slots: null
value: 14
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images: []
