id: adventurer-s-tunic-e3d71
game: diablo-4
type: Chest Armor
tags:
  - diablo-4
  - rare
  - chest armor
rarity: Rare
itemTypeName: Chest Armor
classes: null
slots:
  - Torso
value: 16
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
