id: equipment-defensive-armor-64086
game: diablo-4
type: Trade Agreement
catalog: game
tags:
  - diablo-4
  - normal
  - trade agreement
rarity: Normal
itemTypeName: Trade Agreement
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
