id: avel-hud-nucleus-of-perdition-12ae4
game: diablo-4
type: Back Trophy
tags:
  - diablo-4
  - special
  - back trophy
rarity: Special
itemTypeName: Back Trophy
classes: null
slots:
  - Back Trophy
value: 15
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
