id: moonborn-stallion-c8dba
game: diablo-4
type: item
tags:
  - diablo-4
  - common
  - mount
rarity: Common
itemTypeName: Mount
classes: null
slots: null
value: 40
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
