id: scroll-of-contained-goblins-7ac2d
game: diablo-4
type: Consumable
catalog: game
tags:
  - diablo-4
  - rare
  - consumable
rarity: Rare
itemTypeName: Consumable
classes: null
slots: null
value: 41
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
