id: artificer-s-stone
game: diablo-4
type: Crafting Material
catalog: game
tags:
  - diablo-4
  - special
  - crafting material
rarity: Special
itemTypeName: Crafting Material
classes: null
slots: null
value: 97
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
