id: royal-diamond-045a4
game: diablo-4
type: Gem
catalog: game
tags:
  - diablo-4
  - special
  - gem
rarity: Special
itemTypeName: Gem
classes: null
slots: null
value: 24
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
