id: combat-mk-3-aggressive-22a4b
game: arc-raiders
type: Augment
catalog: game
tags:
  - epic
  - augment
rarity: Epic
subtype: null
value: 5000
stat_block:
  weight: 5
  backpackSlots: 18
  quickUseSlots: 4
  weightLimitKg: 65
  safePocketSlots: 1
  utilityItemSlots: 2
  shieldCompatibility: Light, Heavy, Medium
loadout_slots: []
workbench: Gear Bench III
flavor_text: Restores 2 health every 5 seconds. When damage is taken, the effect
  is paused for 30 seconds.
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
