id: osprey-iv-401be
game: arc-raiders
type: Weapon
tags:
  - rare
  - weapon
rarity: Rare
subtype: null
value: 17000
stat_block:
  range: 80.3
  damage: 45
  weight: 7
  agility: 45.9
  stealth: 12
  fireRate: 17.7
  stability: 85.4
  magazineSize: 8
  reducedReloadTime: 37.5
loadout_slots: []
workbench: Gunsmith III
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
