id: pale-mark-5c642
game: diablo-4
type: Currency
catalog: game
tags:
  - diablo-4
  - unique
  - currency
rarity: Unique
itemTypeName: Currency
classes: null
slots: null
value: 14
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
