id: rank-ii-capstone-cache-d6aa9
game: diablo-4
type: Season Ranking Cache
tags:
  - diablo-4
  - epic
  - season ranking cache
rarity: Epic
itemTypeName: Season Ranking Cache
classes: null
slots: null
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
