id: loyalty-s-mantle-5d78c
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes:
  - Spiritborn
slots:
  - Head
value: 337
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
