id: bjornfang-s-tusks-not-used-we-reuse-for-future-acb67
game: diablo-4
type: Gloves
catalog: game
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes:
  - Druid
slots:
  - Hands
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
