id: goblin-s-magic-kurast-undercity-tributes-96f28
game: diablo-4
type: Goblin Cache
catalog: game
tags:
  - diablo-4
  - common
  - goblin cache
rarity: Common
itemTypeName: Goblin Cache
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
