id: crow-fetish-d9373
game: diablo-4
type: Focus
catalog: game
tags:
  - diablo-4
  - rare
  - focus
rarity: Rare
itemTypeName: Focus
classes:
  - Necromancer
  - Sorcerer
slots:
  - Off-Hand
value: 10
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
