id: 11155111
code: ETH
name: Ethereum Sepolia
architecture: EVM
symbol: ethereum-eth-logo.svg
RPCs:
  - https://ethereum-sepolia-rpc.publicnode.com
  - https://sepolia.drpc.org
  - wss://ethereum-sepolia-rpc.publicnode.com
  - wss://sepolia.drpc.org
explorer: https://sepolia.etherscan.io
