id: bobcat-i-b01b7
game: arc-raiders
type: item
tags:
  - epic
  - weapon
rarity: Epic
subtype: SMG
value: 13000
stat_block:
  ammo: light
  range: 44
  damage: 6
  weight: 7
  agility: 73.1
  stealth: 21
  fireRate: 66.7
  stability: 45.9
  firingMode: Auto
  magazineSize: 20
loadout_slots:
  - weapon
workbench: Weapon Bench 3
flavor_text: Weak against ARC armor plating
ammo_type: light
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
