id: mother-s-embrace-385c7
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - ring
rarity: Legendary
itemTypeName: Ring
classes: null
slots:
  - Ring
value: 87
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
