id: malignant-heart-a4cc3
game: diablo-4
type: Lair Boss Key
catalog: game
tags:
  - diablo-4
  - special
  - lair boss key
rarity: Special
itemTypeName: Lair Boss Key
classes: null
slots: null
value: 298
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
