id: bloody-billy-fa2e2
game: diablo-4
type: item
tags:
  - diablo-4
  - normal
  - pet
rarity: Normal
itemTypeName: Pet
classes: null
slots: null
value: 32
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
