id: sanguivor-blade-of-zir-crucible-4f0fc
game: diablo-4
type: Two-Handed Sword
catalog: game
tags:
  - diablo-4
  - legendary
  - two-handed sword
rarity: Legendary
itemTypeName: Two-Handed Sword
classes:
  - Necromancer
slots:
  - Main Hand
value: 25
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
