id: ahavarion-spear-of-lycander
game: diablo-4
type: Staff
catalog: game
tags:
  - diablo-4
  - mythic
  - staff
rarity: Mythic
itemTypeName: Staff
classes:
  - Druid
  - Sorcerer
slots:
  - Main Hand
value: 66
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
