id: dns-979d3
game: diablo-4
type: Gloves
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes: null
slots:
  - Hands
value: 26
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
