id: renegade-iii-adf7d
game: arc-raiders
type: Weapon
catalog: game
tags:
  - rare
  - weapon
rarity: Rare
subtype: null
value: 13000
stat_block:
  range: 68.8
  damage: 35
  weight: 10
  agility: 55.8
  stealth: 16
  fireRate: 21
  stability: 85.7
  magazineSize: 8
  increasedFireRate: 50
  reducedDurabilityBurnRate: 46
  reducedDispersionRecoveryTime: 33.3
loadout_slots: []
workbench: Gunsmith III
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
