id: sealed-exorcist-s-cache-c5a51
game: diablo-4
type: Quest Item
tags:
  - diablo-4
  - special
  - quest item
rarity: Special
itemTypeName: Quest Item
classes: null
slots: null
value: 15
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
