id: combat-mk-3-flanking-d906e
game: arc-raiders
type: item
tags:
  - epic
  - augment
rarity: Epic
subtype: null
value: 5000
stat_block:
  weight: 3
  augmentSlots: 3
  backpackSlots: 20
  quickUseSlots: 5
  weightLimitKg: 60
  safePocketSlots: 2
  shieldCompatibility: Light
loadout_slots: []
workbench: Gunsmith III
flavor_text: Stowed or unequipped Pistols and Hand Cannon are 33% faster to equip.
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
