id: crest-of-rathma-97d3d
game: diablo-4
type: Trophy
catalog: game
tags:
  - diablo-4
  - normal
  - trophy
rarity: Normal
itemTypeName: Trophy
classes: null
slots:
  - Trophy
value: 14
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
