id: utility-aspects-a8a52
game: diablo-4
type: Bartering Upgrade
catalog: game
tags:
  - diablo-4
  - unique
  - bartering upgrade
rarity: Unique
itemTypeName: Bartering Upgrade
classes: null
slots: null
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
