id: glyph-spirit-387fd
game: diablo-4
type: item
tags:
  - diablo-4
  - rare
  - paragon glyph
rarity: Rare
itemTypeName: Paragon Glyph
classes:
  - Paladin
slots: null
value: 15
images: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
