id: spaceport-warehouse-key-cea6d
game: arc-raiders
type: Key
catalog: game
tags:
  - uncommon
  - key
rarity: Uncommon
subtype: null
value: 100
stat_block:
  weight: 0.25
  stackSize: 1
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations:
  - id: 99789e89-e7cf-3eb8-f80b-387f75e05d78
    map: dam
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
