id: tempest-iii-c7b13
game: arc-raiders
type: Weapon
tags:
  - epic
  - weapon
rarity: Epic
subtype: Assault Rifle
value: 22000
stat_block:
  range: 55.9
  damage: 10
  weight: 11
  agility: 46
  stealth: 14
  fireRate: 36.7
  stability: 78.9
  magazineSize: 25
  reducedReloadTime: 26
loadout_slots: []
workbench: Weapon bench I
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
