id: impure-arc-coolant-c79f7
game: arc-raiders
type: item
tags:
  - uncommon
  - recyclable
rarity: Uncommon
subtype: null
value: 640
stat_block:
  weight: 1
  stackSize: 3
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: ARC
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
