id: elixir-of-advantage-ef09c
game: diablo-4
type: Elixir
tags:
  - diablo-4
  - normal
  - elixir
rarity: Normal
itemTypeName: Elixir
classes: null
slots: null
value: 15
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
