id: dark-citadel-challenger-s-cache-6e67f
game: diablo-4
type: Citadel Cache
tags:
  - diablo-4
  - unique
  - citadel cache
rarity: Unique
itemTypeName: Citadel Cache
classes: null
slots: null
value: 35
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
