id: arpeggio-iii
game: arc-raiders
type: Weapon
catalog: game
tags:
  - uncommon
  - weapon
rarity: Uncommon
subtype: Assault Rifle
value: 11500
stat_block:
  damage: 9.5
  fireRate: 18.3
  range: 55.9
  stability: 78
  agility: 57.3
  stealth: 14
  increasedFireRate: 40
  reducedReloadTime: 25
  reducedDurabilityBurnRate: 46
  weight: 6
  magazineSize: 24
loadout_slots:
  - weapon
workbench: null
flavor_text: null
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
