

#LOG_FILE="/home/x/akao/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='dev@akao.io'
UPGRADE_HASH='ed6d1f34478d49f321e4365b8888f8181f397a10'
USER_PATH='/home/x/akao/node_modules/.bin:/home/x/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/home/x/.nvm/versions/node/v24.15.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/home/x/.nvm/versions/node/v24.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
