id: greater-chestplate-of-the-khazra-4a00c
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - chest armor
rarity: Special
itemTypeName: Chest Armor
classes: null
slots:
  - Torso
value: 30
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
