id: stitcher-i-3f28c
game: arc-raiders
type: Weapon
catalog: game
tags:
  - common
  - weapon
rarity: Common
subtype: SMG
value: 800
stat_block:
  ammo: light
  range: 42.1
  damage: 7
  weight: 5
  agility: 73.8
  stealth: 19
  fireRate: 45.3
  stability: 45.3
  firingMode: Auto
  magazineSize: 20
  reducedReloadTime: 13
loadout_slots:
  - weapon
workbench: Weapon Bench
flavor_text: " Weak against ARC armor plating"
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
