id: firefly-burner-3913a
game: arc-raiders
type: Recyclable
catalog: game
tags:
  - rare
  - recyclable
rarity: Rare
subtype: null
value: 1000
stat_block:
  weight: 0.75
  stackSize: 3
loadout_slots: []
workbench: null
flavor_text: A volatile cansiter that vents fire when shot.
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
