id: exquisite-blood-cache-74a5c
game: diablo-4
type: Rapport Cache
catalog: game
tags:
  - diablo-4
  - unique
  - rapport cache
rarity: Unique
itemTypeName: Rapport Cache
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
