id: infernal-hordes-compass-82e4f
game: diablo-4
type: Nightmare Sigil
tags:
  - diablo-4
  - unique
  - nightmare sigil
rarity: Unique
itemTypeName: Nightmare Sigil
classes: null
slots: null
value: 21
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
