id: griswold-s-opus-87f98
game: diablo-4
type: Sword
catalog: game
tags:
  - diablo-4
  - legendary
  - sword
rarity: Legendary
itemTypeName: Sword
classes:
  - Paladin
slots:
  - Main Hand
  - Off-Hand
value: 1595
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
