id: eagle-finesse-49bd6
game: diablo-4
type: item
tags:
  - diablo-4
  - rare
  - temper manual
rarity: Rare
itemTypeName: Temper Manual
classes:
  - Spiritborn
slots: null
value: 19
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
