id: ph-helm-unique-druid-98-cce1d
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes:
  - Druid
slots:
  - Head
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
