id: enticing-grips-7a178
game: diablo-4
type: Gloves
catalog: game
tags:
  - diablo-4
  - special
  - gloves
rarity: Special
itemTypeName: Gloves
classes:
  - Rogue
slots:
  - Hands
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
