id: esadora-s-overflowing-cameo-0f045
game: diablo-4
type: Amulet
catalog: game
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes:
  - Sorcerer
slots:
  - Neck
value: 362
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
