id: horadric-reward-cache-f31f2
game: diablo-4
type: Cache
tags:
  - diablo-4
  - legendary
  - cache
rarity: Legendary
itemTypeName: Cache
classes: null
slots: null
value: 19
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
