id: bands-of-ichorous-rose-052ce
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes:
  - Rogue
slots:
  - Hands
value: 210
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
