id: the-butcher-s-cleaver-0a81d
game: diablo-4
type: Axe
catalog: game
tags:
  - diablo-4
  - legendary
  - axe
rarity: Legendary
itemTypeName: Axe
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
slots:
  - Main Hand
  - Off-Hand
value: 121
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
