id: shroud-of-false-death-66b90
game: diablo-4
type: item
tags:
  - diablo-4
  - mythic
  - chest armor
rarity: Mythic
itemTypeName: Chest Armor
classes: null
slots:
  - Torso
value: 712
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
