id: free-loadout-augment
game: arc-raiders
type: Augment
catalog: game
tags:
  - common
  - augment
rarity: Common
subtype: null
value: 100
stat_block:
  weightLimit: 35
  backpackSlots: 14
  quickUseSlots: 4
  weightLimitKg: 35
  shieldCompatibility: Light
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
