id: arc-alloy-24fa7
game: arc-raiders
type: item
tags:
  - uncommon
  - topside material
rarity: Uncommon
subtype: null
value: 200
stat_block:
  weight: 0.25
  stackSize: 15
loadout_slots:
  - backpack
  - safePocket
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: ARC
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
