id: marksman-augments-core-74b4c
game: diablo-4
type: Temper Manual
tags:
  - diablo-4
  - common
  - temper manual
rarity: Common
itemTypeName: Temper Manual
classes:
  - Rogue
slots: null
value: 16
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
