id: awoken-adamant-greaves-d18db
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - boots
rarity: Special
itemTypeName: Boots
classes:
  - Barbarian
slots:
  - Feet
value: 16
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
