id: herbal-bandage-f8ee8
game: arc-raiders
type: Quick Use
catalog: game
tags:
  - uncommon
  - quick use
rarity: Uncommon
subtype: null
value: 640
stat_block:
  weight: 0.15
  useTime: 1.5
  duration: 10
  stackSize: 5
  healingPerSecond: 3.5
loadout_slots:
  - backpack
  - quickUse
  - safePocket
workbench: Med Station
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
