id: aegis-8c9ac
game: diablo-4
type: Shield
catalog: game
tags:
  - diablo-4
  - unique
  - shield
rarity: Unique
itemTypeName: Shield
classes:
  - Necromancer
  - Paladin
slots:
  - Off-Hand
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
