id: tactical-mk-1-a7da5
game: arc-raiders
type: Augment
catalog: game
tags:
  - uncommon
  - augment
rarity: Uncommon
subtype: null
value: 640
stat_block:
  weight: 2
  stackSize: 1
  weightLimit: 40
  backpackSlots: 15
  quickUseSlots: 5
  weightLimitKg: 40
  safePocketSlots: 1
  shieldCompatibility: Light, Medium
loadout_slots: []
workbench: Equipment Bench
flavor_text: null
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
