id: seneschal-stone-cache-d540c
game: diablo-4
type: Quest Reward Cache
catalog: game
tags:
  - diablo-4
  - normal
  - quest reward cache
rarity: Normal
itemTypeName: Quest Reward Cache
classes: null
slots: null
value: 14
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
