id: earthbreaker-7cb7b
game: diablo-4
type: Ring
catalog: game
tags:
  - diablo-4
  - legendary
  - ring
rarity: Legendary
itemTypeName: Ring
classes:
  - Druid
slots:
  - Ring
value: 36
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
