id: dns-e4f4e
game: diablo-4
type: Ring
catalog: game
tags:
  - diablo-4
  - legendary
  - ring
rarity: Legendary
itemTypeName: Ring
classes: null
slots:
  - Ring
value: 13
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
