id: venator-iii-c5657
game: arc-raiders
type: item
tags:
  - rare
  - weapon
rarity: Rare
subtype: Pistol
value: 13000
stat_block:
  range: 48.4
  damage: 18
  weight: 5
  agility: 76.4
  stealth: 12
  fireRate: 36.7
  stability: 61.3
  magazineSize: 10
  increasedFireRate: 26
  reducedReloadTime: 33
loadout_slots: []
workbench: Weapon Bench
flavor_text: " Somewhat effective against ARC armor plating"
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
