id: blue-light-stick-e78ec
game: arc-raiders
type: Quick Use
catalog: game
tags:
  - common
  - quick use
rarity: Common
subtype: null
value: 150
stat_block:
  weight: 0.15
  duration: 40
  stackSize: 5
loadout_slots: []
workbench: null
flavor_text: Illumination Radius 7m
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
