id: ph-dummy-rep-tier-item
game: diablo-4
type: Treasure
catalog: game
tags:
  - diablo-4
  - special
  - treasure
rarity: Special
itemTypeName: Treasure
classes: null
slots:
  - Unknown
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
