id: decorated-skull-da38b
game: diablo-4
type: Focus
catalog: game
tags:
  - diablo-4
  - unique
  - focus
rarity: Unique
itemTypeName: Focus
classes:
  - Necromancer
  - Sorcerer
slots:
  - Off-Hand
value: 29
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
