id: melted-heart-of-selig-2b171
game: diablo-4
type: Amulet
catalog: game
tags:
  - diablo-4
  - mythic
  - amulet
rarity: Mythic
itemTypeName: Amulet
classes: null
slots:
  - Neck
value: 474
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
