id: spoils-c2a52
game: diablo-4
type: Back Trophy
catalog: game
tags:
  - diablo-4
  - special
  - back trophy
rarity: Special
itemTypeName: Back Trophy
classes:
  - Barbarian
slots:
  - Back Trophy
value: 13
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
