id: balazan-s-maxtlatl-85068
game: diablo-4
type: Pants
catalog: game
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes:
  - Spiritborn
slots:
  - Legs
value: 73
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
