id: ring-53369
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - ring
rarity: Special
itemTypeName: Ring
classes: null
slots:
  - Ring
value: 676
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
