id: condemnation-f9332
game: diablo-4
type: Chest Armor
catalog: game
tags:
  - diablo-4
  - legendary
  - chest armor
rarity: Legendary
itemTypeName: Chest Armor
classes:
  - Rogue
slots:
  - Torso
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
