id: muzzle-brake-i-324ab
game: arc-raiders
type: Modification
catalog: game
tags:
  - common
  - modification
rarity: Common
subtype: null
value: 640
stat_block:
  weight: 0.25
  reducedVerticalRecoil: 15
loadout_slots:
  - backpack
  - safePocket
workbench: Weapon Bench
flavor_text: "15% Reduced Horizontal Recoil "
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
