id: axolotl-s-smile-e5daf
game: diablo-4
type: Ring
catalog: game
tags:
  - diablo-4
  - unique
  - ring
rarity: Unique
itemTypeName: Ring
classes: null
slots:
  - Ring
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
