id: bone-scythe-f3d51
game: diablo-4
type: Scythe
catalog: game
tags:
  - diablo-4
  - unique
  - scythe
rarity: Unique
itemTypeName: Scythe
classes:
  - Necromancer
slots:
  - Main Hand
value: 22
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
