id: ahu-a4bb6
game: diablo-4
type: Rune of Ritual
tags:
  - diablo-4
  - unique
  - rune of ritual
rarity: Unique
itemTypeName: Rune of Ritual
classes: null
slots: null
value: 402
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
