id: balanced-quarterstaff-dd4ec
game: diablo-4
type: Quarterstaff
catalog: game
tags:
  - diablo-4
  - common
  - quarterstaff
rarity: Common
itemTypeName: Quarterstaff
classes:
  - Spiritborn
slots:
  - Main Hand
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
