id: x-fal-s-corroded-signet-19f16
game: diablo-4
type: Chest Armor
catalog: game
tags:
  - diablo-4
  - legendary
  - chest armor
rarity: Legendary
itemTypeName: Chest Armor
classes: null
slots:
  - Torso
value: 30
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
