id: polearm-b25ae
game: diablo-4
type: Polearm
tags:
  - diablo-4
  - common
  - polearm
rarity: Common
itemTypeName: Polearm
classes:
  - Barbarian
  - Druid
  - Spiritborn
slots:
  - Main Hand
value: 23
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
