id: matriarch-reactor
game: arc-raiders
type: Recyclable
catalog: game
tags:
  - legendary
  - recyclable
rarity: Legendary
subtype: null
value: 13000
stat_block:
  weight: 10
loadout_slots: []
workbench: null
flavor_text: "Used to Craft: Aphelion"
ammo_type: null
shield_type: null
loot_area: ARC
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
