id: governing-stone-focus-fire
game: diablo-4
type: Senechal Power Module
catalog: game
tags:
  - diablo-4
  - epic
  - senechal power module
rarity: Epic
itemTypeName: Senechal Power Module
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
