id: avatar-of-trag-oul-278f3
game: diablo-4
type: Body Marking
catalog: game
tags:
  - diablo-4
  - normal
  - body marking
rarity: Normal
itemTypeName: Body Marking
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
