id: rage-of-harrogath-009ae
game: diablo-4
type: Pants
catalog: game
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes:
  - Barbarian
slots:
  - Legs
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
