id: osprey-i-ac1ba
game: arc-raiders
type: Weapon
catalog: game
tags:
  - rare
  - weapon
rarity: Rare
subtype: Sniper Rifle
value: 7000
stat_block:
  ammo: medium
  range: 80.3
  damage: 45
  weight: 7
  agility: 45.9
  stealth: 12
  fireRate: 17.7
  stability: 85.4
  firingMode: Single
  magazineSize: 8
loadout_slots:
  - weapon
workbench: Weapon Bench 2
flavor_text: Somewhat effective against ARC armor plating
ammo_type: medium
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
