id: rod-of-divination-ed578
game: diablo-4
type: Staff
catalog: game
tags:
  - diablo-4
  - special
  - staff
rarity: Special
itemTypeName: Staff
classes:
  - Sorcerer
slots:
  - Main Hand
value: 19
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
