id: fractured-winterglass-50f46
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes:
  - Sorcerer
slots:
  - Legs
value: 15
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
