id: alien-duck-006e2
game: arc-raiders
type: item
tags:
  - uncommon
  - trinket
rarity: Uncommon
subtype: null
value: 1000
stat_block:
  weight: 0.3
  stackSize: 15
loadout_slots: []
workbench: null
flavor_text: Can be thrown to create noise.
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
