contracts:
  - chain: 56
    name: PancakeswapV3Factory
    type: factory
    dex: Pancakeswap
    version: V3
    ABI: PancakeswapV3Factory
    address: "0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865"
  - chain: 56
    name: PancakeswapV3Router
    type: router
    dex: Pancakeswap
    version: V3
    ABI: PancakeswapV3Router
    address: "0x13f4EA83D0bd40E75C8222255bc855a974568Dd4"
  - chain: 56
    name: PancakeswapV3PositionManager
    type: positionManager
    dex: Pancakeswap
    version: V3
    ABI: PancakeswapV3PositionManager
    address: "0x46A15B0b27311cedF172AB29E4f4766fbE7F4364"
  - chain: 56
    name: PancakeswapQuoter
    type: quoter
    dex: Pancakeswap
    version: V3
    ABI: PancakeswapQuoter
    address: "0xb048bbc1ee6b733fffcfb9e9cef7375518e25997"
