id: gospel-of-the-devotee-7323a
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - focus
rarity: Legendary
itemTypeName: Focus
classes:
  - Necromancer
slots:
  - Off-Hand
value: 46
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
