id: confession-beacon-b07b5
game: diablo-4
type: item
tags:
  - diablo-4
  - special
  - focus
rarity: Special
itemTypeName: Focus
classes:
  - Necromancer
  - Sorcerer
slots:
  - Off-Hand
value: 16
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
