id: artificer-s-stone-20d63
game: diablo-4
type: Crafting Material
tags:
  - diablo-4
  - special
  - crafting material
rarity: Special
itemTypeName: Crafting Material
classes: null
slots: null
value: 123
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
