id: deathspeaker-s-pendant-2b314
game: diablo-4
type: Amulet
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes:
  - Necromancer
slots:
  - Neck
value: 44
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
