id: banished-lord-s-talisman-87c28
game: diablo-4
type: Amulet
catalog: game
tags:
  - diablo-4
  - legendary
  - amulet
rarity: Legendary
itemTypeName: Amulet
classes: null
slots:
  - Neck
value: 174
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
