id: doom-orb-45047
game: diablo-4
type: Witch Power
catalog: game
tags:
  - diablo-4
  - legendary
  - witch power
rarity: Legendary
itemTypeName: Witch Power
classes: null
slots: null
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
