id: pointed-finger-grimoire-3389c
game: diablo-4
type: Crafting Recipe
catalog: game
tags:
  - diablo-4
  - common
  - crafting recipe
rarity: Common
itemTypeName: Crafting Recipe
classes: null
slots: null
value: 10
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
