id: ferro-iv-26869
game: arc-raiders
type: Weapon
tags:
  - common
  - weapon
rarity: Common
subtype: null
value: 2900
stat_block:
  range: 53.1
  damage: 40
  weight: 8
  agility: 31.1
  stealth: 8
  fireRate: 6.6
  stability: 78.1
  magazineSize: 1
  reducedReloadTime: 39
loadout_slots:
  - weapon
workbench: Weapon Bench
flavor_text: Very effective against ARC armor plating
ammo_type: Heavy
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
