id: dark-citadel-gear-cache
game: diablo-4
type: Citadel Vendor Cache
catalog: game
tags:
  - diablo-4
  - rare
  - citadel vendor cache
rarity: Rare
itemTypeName: Citadel Vendor Cache
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
