id: slayer-s-equipment-cache-53f6d
game: diablo-4
type: Season Ranking Cache
tags:
  - diablo-4
  - legendary
  - season ranking cache
rarity: Legendary
itemTypeName: Season Ranking Cache
classes: null
slots: null
value: 18
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
