id: iron-skin-elixir-94710
game: diablo-4
type: Elixir
catalog: game
tags:
  - diablo-4
  - normal
  - elixir
rarity: Normal
itemTypeName: Elixir
classes: null
slots: null
value: 11
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
