id: khazra-horn-45bfa
game: diablo-4
type: Currency
catalog: game
tags:
  - diablo-4
  - special
  - currency
rarity: Special
itemTypeName: Currency
classes: null
slots: null
value: 50
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
