id: killer-s-guise-da6d8
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - normal
  - helm
rarity: Normal
itemTypeName: Helm
classes: null
slots:
  - Head
value: 19
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
