id: the-mortacrux-75a78
game: diablo-4
type: Dagger
tags:
  - diablo-4
  - legendary
  - dagger
rarity: Legendary
itemTypeName: Dagger
classes:
  - Necromancer
slots:
  - Main Hand
  - Off-Hand
value: 45
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
