id: crown-of-lucion-e2ac0
game: diablo-4
type: Boots
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes: null
slots:
  - Feet
value: 27
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
