id: il-toro-i-2be29
game: arc-raiders
type: item
tags:
  - uncommon
  - weapon
rarity: Uncommon
subtype: Shotgun
value: 5000
stat_block:
  ammo: shotgun
  range: 20
  damage: 67.5
  weight: 8
  agility: 61.1
  stealth: 18
  fireRate: 14.3
  stability: 80.6
  firingMode: Single
  magazineSize: 5
loadout_slots:
  - weapon
workbench: Weapon Bench 1
flavor_text: Somewhat effective against ARC armor plating
ammo_type: shotgun
shield_type: null
loot_area: null
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
