id: mantle-of-mountain-s-fury-ea5d5
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - chest armor
rarity: Legendary
itemTypeName: Chest Armor
classes:
  - Barbarian
slots:
  - Torso
value: 302
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
