name: localhost
brand:
  text: /statics/sites/localhost/images/text.svg
  symbol: /statics/sites/localhost/images/symbol.svg
favicon: /statics/sites/localhost/images/favicon.svg
env: development
locale: en
fiat: USD
chains: [ 1, 56, 97, 11155111 ]
peers: [ "http://localhost:8765/gun" ]
market:
  pub: ArSykNJvsUG9FwqCdDv23vtjhXPFGwr0U-crM1tnaAI.C7YfgkDoUK3kz_GMycx78KyYwu7RANKkrhCfMsDehYI
  epub: nK2HMGNDBq3GMEM_moQG256TLzvVklHHrSrdsVCQCuQ.49mYdUw1AvBdBf_61iFTmVev6_yvRpENIJUe3PWCbSg