id: gate-of-the-red-dawn-9477b
game: diablo-4
type: Shield
tags:
  - diablo-4
  - legendary
  - shield
rarity: Legendary
itemTypeName: Shield
classes:
  - Paladin
slots:
  - Off-Hand
value: 110
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
