id: breeches-of-baleful-intent
game: diablo-4
type: Pants
catalog: game
tags:
  - diablo-4
  - unique
  - pants
rarity: Unique
itemTypeName: Pants
classes: null
slots:
  - Legs
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
