id: ph-9436f
game: diablo-4
type: Pants
tags:
  - diablo-4
  - legendary
  - pants
rarity: Legendary
itemTypeName: Pants
classes:
  - Rogue
slots:
  - Legs
value: 19
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
