id: leaper-pulse-unit-1fd97
game: arc-raiders
type: Throwable
tags:
  - epic
  - throwable
rarity: Epic
subtype: null
value: 5000
stat_block:
  damage: 100
  radius: 10
  weight: 1
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: ARC
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
