id: expired-pasta-37729
game: arc-raiders
type: item
tags:
  - common
  - trinket
rarity: Common
subtype: null
value: 1000
stat_block:
  weight: 0.1
  healing: 15
  useTime: 1
  stackSize: 15
loadout_slots: []
workbench: null
flavor_text: null
ammo_type: null
shield_type: null
loot_area: Commercial, Residential
sources: null
locations: []
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
