id: shard-of-agony-e5815
game: diablo-4
type: Lair Boss Key
tags:
  - diablo-4
  - special
  - lair boss key
rarity: Special
itemTypeName: Lair Boss Key
classes: null
slots: null
value: 366
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
