id: screamseal-4ac44
game: diablo-4
type: item
tags:
  - diablo-4
  - unique
  - ring
rarity: Unique
itemTypeName: Ring
classes: null
slots:
  - Ring
value: 15
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
