id: flameweaver-414ab
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - gloves
rarity: Legendary
itemTypeName: Gloves
classes:
  - Sorcerer
slots:
  - Hands
value: 34
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
