id: dns-565b9
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - sword
rarity: Legendary
itemTypeName: Sword
classes:
  - Barbarian
  - Druid
  - Necromancer
  - Paladin
  - Rogue
  - Sorcerer
slots:
  - Main Hand
  - Off-Hand
value: 15
images: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
