id: 100-000-steps-6822d
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Barbarian
slots:
  - Feet
value: 187
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
