id: ph-godslayer-crown-3abe1
game: diablo-4
type: Helm
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes: null
slots:
  - Head
value: 76
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
