id: okun-s-catalyst-c1216
game: diablo-4
type: Focus
tags:
  - diablo-4
  - legendary
  - focus
rarity: Legendary
itemTypeName: Focus
classes:
  - Sorcerer
slots:
  - Off-Hand
value: 182
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
