id: 1
code: ETH
name: Ethereum
architecture: EVM
symbol: ethereum-eth-logo.svg
RPCs:
  - https://eth.drpc.org
  - https://rpc.mevblocker.io
  - https://eth.blockrazor.xyz
  - https://eth.merkle.io
  - https://1rpc.io/eth
  - wss://ethereum-rpc.publicnode.com
explorer: https://etherscan.io
