id: herald-of-zakarum-2e319
game: diablo-4
type: Shield
catalog: game
tags:
  - diablo-4
  - legendary
  - shield
rarity: Legendary
itemTypeName: Shield
classes:
  - Paladin
slots:
  - Off-Hand
value: 448
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
