id: bloodless-scream-d2e96
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - two-handed scythe
rarity: Legendary
itemTypeName: Two-Handed Scythe
classes:
  - Necromancer
slots:
  - Main Hand
value: 142
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
