id: caged-heart
game: diablo-4
type: Caged Heart
catalog: game
tags:
  - diablo-4
  - normal
  - caged heart
rarity: Normal
itemTypeName: Caged Heart
classes: null
slots: null
value: 17
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
