id: rotting-lightbringer-13a4e
game: diablo-4
type: Two-Handed Mace
tags:
  - diablo-4
  - legendary
  - two-handed mace
rarity: Legendary
itemTypeName: Two-Handed Mace
classes:
  - Druid
slots:
  - Main Hand
value: 467
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
