id: balazan-s-maxtlatl-88fd7
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes:
  - Spiritborn
slots:
  - Feet
value: 21
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
