id: marshal-s-servo-greaves-daeaf
game: diablo-4
type: Pants
catalog: game
tags:
  - diablo-4
  - special
  - pants
rarity: Special
itemTypeName: Pants
classes:
  - Barbarian
slots:
  - Legs
value: 12
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
