id: eagle-finesse-79687
game: diablo-4
type: Temper Manual
tags:
  - diablo-4
  - unique
  - temper manual
rarity: Unique
itemTypeName: Temper Manual
classes:
  - Spiritborn
slots: null
value: 22
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
