id: gohr-s-devastating-grips-05d07
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes:
  - Barbarian
slots:
  - Head
value: 15
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
