id: ph-template-unique-7d501
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - ring
rarity: Legendary
itemTypeName: Ring
classes:
  - Spiritborn
slots:
  - Ring
value: 16
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
