id: x-fal-s-corroded-signet-f9e07
game: diablo-4
type: Boots
catalog: game
tags:
  - diablo-4
  - legendary
  - boots
rarity: Legendary
itemTypeName: Boots
classes: null
slots:
  - Feet
value: 30
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
