id: staff-of-endless-rage-08bb7
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - helm
rarity: Legendary
itemTypeName: Helm
classes:
  - Sorcerer
slots:
  - Head
value: 19
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
