id: willbreaker-tome-6c8c7
game: diablo-4
type: item
tags:
  - diablo-4
  - legendary
  - crafting recipe
rarity: Legendary
itemTypeName: Crafting Recipe
classes: null
slots: null
value: 15
images:
  - 0.webp
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
