id: vita-spray-0d20a
game: arc-raiders
type: Quick Use
catalog: game
tags:
  - epic
  - quick use
rarity: Epic
subtype: null
value: 3400
stat_block:
  weight: 1
  duration: 100
  stackSize: 1
  healingPerSecond: 10
loadout_slots:
  - backpack
  - quickUse
  - safePocket
workbench: Med Station
flavor_text: "Health Per Second: 10/s"
ammo_type: null
shield_type: null
loot_area: null
sources: null
locations: []
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
