id: thornblood-diadem-a1589
game: diablo-4
type: Helm
catalog: game
tags:
  - diablo-4
  - special
  - helm
rarity: Special
itemTypeName: Helm
classes:
  - Spiritborn
slots:
  - Head
value: 16
configs:
  min:
    quantity: null
    value: null
  max:
    quantity: null
    value: null
  step: null
  type: item
images:
  - 0.webp
